### PR TITLE
Wrap Echo framework logger that could be used in microservices

### LINKED ISSUE #34: Echo logger wrapper
Implement a wrapper for Coop logger that can be passed to the Echo framework to relate Echo logs with Datadog APM.

### PR DESCRIPTION
**Pull request by LinMAD**
Closes #34

### CODE REVIEW

**Review by DylanWatson44 — DISMISSED** [review]

**Review by DylanWatson44 — DISMISSED** [review]
log "github.com/coopnorge/go-logger"
	echo "github.com/labstack/gommon/log"
	
These aliases are a bit confusing, but it doesn't matter too much

**Comment by LinMAD** [comment]
> ```
> log "github.com/coopnorge/go-logger"
> echo "github.com/labstack/gommon/log"
> ```
> 
> These aliases are a bit confusing, but it doesn't matter too much

@DylanWatson44 I know, any better ideas? :) It must be in set pckg `adapter/echo` since your project may not use `echo` so go mods will not fetch it

**Comment by DylanWatson44** [comment]
> > ```
> > log "github.com/coopnorge/go-logger"
> > echo "github.com/labstack/gommon/log"
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > These aliases are a bit confusing, but it doesn't matter too much
> 
> @DylanWatson44 I know, any better ideas? :) It must be in set pckg `adapter/echo` since your project may not use `echo` so go mods will not fetch it

go_logger and gommon_log maybe. But you can merge as is

**Comment by LinMAD** [comment]
> > > ```
> > > log "github.com/coopnorge/go-logger"
> > > echo "github.com/labstack/gommon/log"
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > These aliases are a bit confusing, but it doesn't matter too much
> > 
> > 
> > @DylanWatson44 I know, any better ideas? :) It must be in set pckg `adapter/echo` since your project may not use `echo` so go mods will not fetch it
> 
> go_logger and gommon_log maybe. But you can merge as is

@DylanWatson44 go_logger name crossing with the repository, not cool for adapter then. To merge I need anyway 2 approves, so maybe `labstack_logger`?

**Comment by DylanWatson44** [comment]
> > > > ```
> > > > log "github.com/coopnorge/go-logger"
> > > > echo "github.com/labstack/gommon/log"
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > These aliases are a bit confusing, but it doesn't matter too much
> > > 
> > > 
> > > @DylanWatson44 I know, any better ideas? :) It must be in set pckg `adapter/echo` since your project may not use `echo` so go mods will not fetch it
> > 
> > 
> > go_logger and gommon_log maybe. But you can merge as is
> 
> @DylanWatson44 go_logger name crossing with the repository, not cool for adapter then. To merge I need anyway 2 approves, so maybe `labstack_logger`?

Sure that works

**Review by DylanWatson44 — APPROVED** [review]

**Review by martinostvik — APPROVED** [review]

**Pull request merged**
