### PR TITLE
feat: Use regular expressions to parse the log statement

### PR DESCRIPTION
**Pull request by nhhagen**

### CODE REVIEW

**Comment by bendiknesbo** [comment]
This PR ties us very close to the **current** log-format of the Datadog lib, and makes it brittle if it changes. The gain, as far as I see it, is very minimal; mostly moving some parts of the `msg` into other fields in the log.

What issue are you trying to solve here?

**Comment by nhhagen** [comment]
I'm wanted to address the noise in the `msg` field that in the current implementation causes quite some noise, but I'm fine with dropping this.

**Comment by bendiknesbo** [comment]
FWIW: Datadog has already implemented a leveled logger in their `v2-dev` branch: https://github.com/DataDog/dd-trace-go/pull/2480

**Comment by nhhagen** [comment]
Then we wait for that and upgrade instead.

**Pull request closed without merging**
